apiVersion: v1
kind: Service
metadata:
  name: assignment-agentic-ai-service
  namespace: default
  labels:
    app: assignment-agentic-ai
spec:
  type: NodePort
  selector:
    app: assignment-agentic-ai
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 31080
